// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmkR8Md_x8GoUtJvT4VZI6N5B-4TNElU',
    appId: '1:306321474961:web:3594739d27d233f28fc630',
    messagingSenderId: '306321474961',
    projectId: 'crudmahasiswa-bcdd6',
    authDomain: 'crudmahasiswa-bcdd6.firebaseapp.com',
    storageBucket: 'crudmahasiswa-bcdd6.firebasestorage.app',
    measurementId: 'G-TM4HWJC7WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-wXi7BWmpcFe04nQ3utIF55kWhilRmOQ',
    appId: '1:306321474961:android:91b7c0e8b39b0dd48fc630',
    messagingSenderId: '306321474961',
    projectId: 'crudmahasiswa-bcdd6',
    storageBucket: 'crudmahasiswa-bcdd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfqbXqnuSkE9dKH5hLUZGoQdzqD2fx-6E',
    appId: '1:306321474961:ios:231b3c14cfe554a78fc630',
    messagingSenderId: '306321474961',
    projectId: 'crudmahasiswa-bcdd6',
    storageBucket: 'crudmahasiswa-bcdd6.firebasestorage.app',
    iosBundleId: 'com.example.crudSederhana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfqbXqnuSkE9dKH5hLUZGoQdzqD2fx-6E',
    appId: '1:306321474961:ios:231b3c14cfe554a78fc630',
    messagingSenderId: '306321474961',
    projectId: 'crudmahasiswa-bcdd6',
    storageBucket: 'crudmahasiswa-bcdd6.firebasestorage.app',
    iosBundleId: 'com.example.crudSederhana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXmkR8Md_x8GoUtJvT4VZI6N5B-4TNElU',
    appId: '1:306321474961:web:d2ee4aa04d44ec118fc630',
    messagingSenderId: '306321474961',
    projectId: 'crudmahasiswa-bcdd6',
    authDomain: 'crudmahasiswa-bcdd6.firebaseapp.com',
    storageBucket: 'crudmahasiswa-bcdd6.firebasestorage.app',
    measurementId: 'G-M5LDL3WEF0',
  );
}